---
DEVICE: gpu
learning:
  HYPER_EVALS: 10
  LEARNING_RATE: 1
  objective: rmse
  LEARN_METRICS_TASK: min
  boosting: gbdt #gbdt #dart
  N_JOBS: -1
  N_ROUNDS: 2000
CV:
  n_splits: 5
  train_size: 0.8
  test_size: 0.2
