version: "2.4"
services:
  linear:
    build:
      context: .
      dockerfile: dockerfile.lr
    runtime: nvidia
    volumes:
      - .:/app
  lgbm:
    build:
      context: .
      dockerfile: dockerfile.lgbm
    runtime: nvidia
    volumes:
      - .:/app
  lgbm_cv:
    build:
      context: .
      dockerfile: dockerfile.lgbm_cv
    runtime: nvidia
    volumes:
      - .:/app
  lgbm_kfold:
    build:
      context: .
      dockerfile: dockerfile.lgbm_kfold
    runtime: nvidia
    volumes:
      - .:/app